WebTeleCitas/WebTeleCitas/Controllers/DependientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebTeleCitas.Controllers
{
    public class DependientesController : Controller
    {
        public IActionResult Index()
        {
            return View("../Pages/Dependientes/Index");
        }
    }
}

WebTeleCitas/WebTeleCitas/Controllers/HCitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model;
using Model.Entidad;
using Service;
using WebTeleCitas.ViewModels;

namespace WebTeleCitas.Controllers
{
    public class HCitasController : Controller
    {
        private readonly IPersonaService _servicePer;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;
        private readonly IErrorService _serviceError;

        public HCitasController(IPersonaService servicePer, IHttpContextAccessor httpContextAccessor, IErrorService serviceError)
        {
            this._servicePer = servicePer;
            _httpContextAccessor = httpContextAccessor;
            _serviceError = serviceError;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //valida session
            var tdocumento = _session.GetString("tipodocumento");
            var documento = _session.GetString("documento");
            if (tdocumento == null || documento == null)
            { 
                return RedirectToAction("Login", "Persona");
            }
            //fin

            VmPersona permostrar = new VmPersona();
            try
            {
                Persona per = _servicePer.GetPersonasXTipNumero(tdocumento, documento);
                ViewBag.NOMBRE = per.PNOMBRE;
                
                permostrar.PNOMBRE = per.PNOMBRE;
                permostrar.ID = per.ID;
                HttpContext.Session.SetString("idpersona", per.ID.ToString());

                permostrar.SEXO = per.SXO == "M" ? "MASCULINO" : "FEMENINO";
                permostrar.EDAD = (DateTime.Today.AddTicks(-per.FNCMNTO.Ticks).Year - 1).ToString();
                permostrar.PSO = (per.PSO == null ? "0" : per.PSO);
                permostrar.ALTRA = (per.ALTRA == null ? "0" : per.ALTRA);
                permostrar.TSNGRE = (per.TSNGRE == null ? string.Empty : per.TSNGRE);


            }
            catch (Exception ex)
            {
                Errores("Persona", "Session", ex.Message.ToString());
                return RedirectToAction("Login", "Persona");
            }
            
            return View("../Pages/Inicio/Index", permostrar);
        }

        public void Errores(string tabla, string paquete, string descrip)
        {
            Error e = new Error();
            e.NTBLA = tabla;
            e.NPKGPD = paquete;
            e.DSCRPCN = descrip;
            _serviceError.InsertError(e);
        }

    }
}

WebTeleCitas/WebTeleCitas/Controllers/HistoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebTeleCitas.Controllers
{
    public class HistoriaController : Controller
    {
        public IActionResult Index()
        {
            return View("../Pages/Historia/Index");
        }
    }
}

WebTeleCitas/WebTeleCitas/Controllers/ProgramadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebTeleCitas.Controllers
{
    public class ProgramadasController : Controller
    {
        public IActionResult Index()
        {
            return View("../Pages/Programadas/Index");
        }
    }
}

WebTeleCitas/WebTeleCitas/Views/Shared/_Layout.cshtml
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/style.css">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png">
    <style type="text/css">
        .chartjs-render-monitor {
            animation: chartjs-render-animation 1ms
        }

        .chartjs-size-monitor,
        .chartjs-size-monitor-expand,
        .chartjs-size-monitor-shrink {
            position: absolute;
            direction: ltr;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            overflow: hidden;
            pointer-events: none;
            visibility: hidden;
            z-index: -1
        }

            .chartjs-size-monitor-expand > div {
                position: absolute;
                width: 1000000px;
                height: 1000000px;
                left: 0;
                top: 0
            }

            .chartjs-size-monitor-shrink > div {
                position: absolute;
                width: 200%;
                height: 200%;
                left: 0;
                top: 0
            }
    </style>
    <style rel="stylesheet">
        input[type="text"], select {
            text-transform: uppercase !important;
        }

            input[type="text"].cemail {
                text-transform: none !important;
            }

        ::placeholder {
            text-transform: none !important;
        }

        .datepicker td, .datepicker th {
            width: 1.5em;
            height: 1.5em;
        }

        .input-group-text {
            /* padding: .375rem .55rem !important;*/
            padding: .1rem .55rem !important;
        }

        #user .input-group-append .input-group-text, .input-group-prepend .input-group-text {
            color: #5a7ebf;
        }

        #user .input-group .input-group-prepend .input-group-text > i {
            color: #5a7ebf;
            width: 15px !important;
        }
    </style>
    @*jquery*@
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    @*jquery*@
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    @*fuentes*@
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    @*Wizard*@
    <link rel="stylesheet" href="~/css/easyWizard.css">
    <script src="~/js/easyWizard.js"></script>
    @*EstiloAdm*@
    <link rel="stylesheet" href="~/css/styleAdm.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <script src="~/js/jsUtil.js"></script>
    <script src="~/js/jquery.validationEngine-es.js" type="text/javascript" charset="utf-8"></script>
    <script src="~/js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
    <link href="~/css/validationEngine.jquery.css" rel="stylesheet" type="text/css" />
</head>

<body class="sidebar-icon-only">
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo mr-5"  asp-controller="HCitas" asp-action="Index"><img src="~/images/logo.svg" class="mr-2" alt="logo"></a>
                <a class="navbar-brand brand-logo-mini" asp-controller="HCitas" asp-action="Index"><img src="~/images/logo-mini.svg" alt="logo"></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="ti-view-list"></span>
                </button>

                <ul class="navbar-nav navbar-nav-right">


                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            <img src="~/images/faces/face28.jpg" alt="profile">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="~/pages/citas/Index.html">
                                <i class="ti-power-off text-primary"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="ti-view-list"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="HCitas" asp-action="Index">
                            <i class="ti-home menu-icon"></i>
                            <span class="menu-title">Inicio</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Citas" asp-action="Index">
                            <i class="ti-heart menu-icon"></i>
                            <span class="menu-title">Generar Cita</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  asp-controller="Programadas" asp-action="Index">
                            <i class="ti-calendar menu-icon"></i>
                            <span class="menu-title">Citas programadas</span>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  asp-controller="Historia" asp-action="Index">
                            <i class="ti-clipboard menu-icon"></i>
                            <span class="menu-title">Historial de Citas</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  asp-controller="Dependientes" asp-action="Index">
                            <i class="ti-user menu-icon"></i>
                            <span class="menu-title">Dependientes</span>
                        </a>

                    </li>

                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="#" target="_blank"></a></span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/js/off-canvas.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/template.js"></script>
    <script src="~/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/js/dashboard.js"></script>
    <!-- End custom js for this page-->
    @RenderSection("Scripts", required: false)
 </body>
</html>

WebTeleCitas/WebTeleCitas/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="~/js/jsUtil.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--holi-->
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    @*<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">*@
    <style rel="stylesheet">
        input[type="text"], select {
            text-transform: uppercase !important;
        }
        input[type="text"].cemail{
            text-transform: none !important;
        }
        ::placeholder {
            text-transform: none !important;
        }

        .datepicker td, .datepicker th {
            width: 1.5em;
            height: 1.5em;
        }

        .input-group-text {
            padding: .375rem .55rem;
        }

        #user .input-group .input-group-prepend .input-group-text > i {
            color: #5a7ebf;
            width: 15px;
        }
    </style>
    <script src="~/js/jquery.validationEngine-es.js" type="text/javascript" charset="utf-8"></script>
    <script src="~/js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
    <link href="~/css/validationEngine.jquery.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            @RenderBody()
        </div>
    </div>
</body>
<!--holi-->

</html>